### PR TITLE
Fix 0.2.4

### PR DESCRIPTION
**Pull request by rish9511**
Fix:
- usability issues (storing lastRun.xml in user-config location, updating mavenParameters on 
'esc' key event)
- issues that cause installer to fail to work properly

### CODE REVIEW

**Comment by lparsons** [comment]
Glad to see these issues being addressed, thanks @rish9511! Is the build process for Windows and/or MacOS documented somewhere? I would love to test some of these things out, but at the moment that part seems pretty opaque. I don't know how you guys create the installers and thus can't really test stuff like this.

**Comment by rish9511** [comment]
@lparsons  
build process for windows and mac can be found [here](https://github.com/ElucidataInc/ElMaven#build) 
Since you want to build this branch, you will have to fetch and checkout to `fix_0.2.4` branch  after you have cloned the repo

 > I don't know how you guys create the installers and thus can't really test stuff like this.

This process has not been documented as of now

However If you don't want to go through the build process, we can provide you the installer for this specific branch. Whatever you prefer.

**Comment by rish9511** [comment]
@sahil21  can be merged , right?

**Comment by lparsons** [comment]
@rish9511 Good point about the build process. Assuming that is actually what is used to build the releases, that's great and is quite useful. However, without the installer, I can't really test this fix. I guess it's a manual thing right now? It would be nice to have some CI systems at least build executables, if not the installers. Is there an effort towards that goal? And thanks, looking forward to stable installer I can distribute to group (we've had to hold off getting the lab using the software due to serious issues like this one).

**Comment by rish9511** [comment]
@lparsons 
> I guess it's a manual thing right now? 

Yes, we prepare installers manually.

>  It would be nice to have some CI systems at least build executables, if not the installers. Is there an effort towards that goal?

We want to do something similar in the coming time. As of now we use Travis for CI(automated build + tests) 

> And thanks, looking forward to stable installer I can distribute to group (we've had to hold off getting the lab using the software due to serious issues like this one).

Thanks for reporting all the issues  😃

**Comment by lparsons** [comment]
Thanks, this looks like it addresses #574 then, though I'll need to wait for an installer to truly test.

**Pull request merged**
